In [1]:
import pandas as pd

In [17]:
# Read the excel worksheets into one dataframe
current_residence_df = pd.concat(pd.read_excel (".\Resources\county-to-county-2015-2019-current-residence-sort.xlsx", sheet_name=None), ignore_index=True)

In [3]:
# View top 10 rows of the dataframe
current_residence_df.head(10)

,Table with column headers in rows 2 through 4.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,Current Residence State Code,Current Residence FIPS County Code,Residence 1 Year Ago State/U.S. Island Area/Fo...,Residence 1 Year Ago FIPS County Code,State of Current Residence,County of Current Residence,County of Current Residence,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Movers in County-to-County Flow,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,Population 1 Year and Over,NaN,Nonmovers,NaN,...,Movers within Same County,NaN,"Movers to Different County, Same State",NaN,Movers to Different State,NaN,Movers to Puerto Rico,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,Estimate,MOE,Estimate,MOE,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
3,001,001,001,003,Alabama,Autauga County,54699,172,48066,987,...,13004,1466,3133,598,5592,827,NaN,NaN,25,26
4,001,001,001,005,Alabama,Autauga County,54699,172,48066,987,...,2325,523,1210,329,325,160,NaN,NaN,4,8
5,001,001,001,007,Alabama,Autauga County,54699,172,48066,987,...,784,352,1184,408,132,88,NaN,NaN,10,16
6,001,001,001,009,Alabama,Autauga County,54699,172,48066,987,...,2024,425,1818,436,583,209,NaN,NaN,3,6
7,001,001,001,015,Alabama,Autauga County,54699,172,48066,987,...,11467,1413,4162,565,2459,577,67,78,2,4
8,001,001,001,021,Alabama,Autauga County,54699,172,48066,987,...,2835,814,1234,377,462,231,NaN,NaN,11,16
9,001,001,001,025,Alabama,Autauga County,54699,172,48066,987,...,1146,376,413,178,292,206,NaN,NaN,34,52

In [4]:
# View last 10 rows of the dataframe
current_residence_df.tail(10)

,Table with column headers in rows 2 through 4.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
278791,072,153,072,151,Puerto Rico,Yauco Municipio,35149,127,33995,457,...,1253,536,766,408,1317,447,NaN,NaN,71,107
278792,072,153,CAR,NaN,Puerto Rico,Yauco Municipio,35149,127,33995,457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,34
278793,072,153,SAM,NaN,Puerto Rico,Yauco Municipio,35149,127,33995,457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,86
278794,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278795,"1Includes Puerto Rico, U.S. Island Areas, and ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278796,2Estimate is movers within the United States f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278797,Blank cells represent estimates that are not a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278798,MOE - Margin of error based on 90% confidence ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278799,The Census Bureau reviewed this data product f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278800,"Source: U.S. Census Bureau, 2015-2019 American...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# View list of columns
list(current_residence_df.columns.values)

['Table with column headers in rows 2 through 4.',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37']

In [6]:
#Rename columns and replace spaces with underscore
current_residence_df.rename(columns = {"Table with column headers in rows 2 through 4.":"Current_Residence_State_Code",
                            "Unnamed: 1":"Current_Residence_FIPS_County_Code",
                            "Unnamed: 2":"Previous_Residence_State/U.S._Island Area/Foreign_Region_Code",
                            "Unnamed: 3":"Previous_Residence_FIPS_County_Code",
                            "Unnamed: 4":"Current_Residence_State",
                            "Unnamed: 5":"Current_Residence_County",
                            "Unnamed: 6":"Current_Residence_County_Population",
                            "Unnamed: 7":"Current_Residence_County_Population_1_Year_and_Over_MOE",
                            "Unnamed: 8":"Current_Residence_County_Nonmovers",
                            "Unnamed: 9":"Current_Residence_County_Nonmovers_MOE",
                            "Unnamed: 10":"Current_Residence_Movers_within_US",
                            "Unnamed: 11":"Current_Residence_Movers_within_United_States_1",
                            "Unnamed: 12":"Current_Residence_Movers_within_Same_County",
                            "Unnamed: 13":"Current_Residence_Movers_within_Same_County_MOE",
                            "Unnamed: 14":"Current_Residence_Movers_from_Different_County_Same_State",
                            "Unnamed: 15":"Current_Residence_Movers_from_Different_County_Same_State_MOE",
                            "Unnamed: 16":"Current_Residence_Movers_from_Different_State",
                            "Unnamed: 17":"Current_Residence_Movers_from_Different_State_MOE",
                            "Unnamed: 18":"Current_Residence_Movers_from_Abroad",
                            "Unnamed: 19":"Current_Residence_Movers_from_Abroad_MOE",
                            "Unnamed: 20":"Previous_Residence_Movers_within_US_or_PR",
                            "Unnamed: 21":"Previous_Residence_County",
                            "Unnamed: 22":"Previous_Residence_County_Population",
                            "Unnamed: 23":"Previous_Residence_County_Population_1_Year_and_Over_MOE",
                            "Unnamed: 24":"Previous_Residence_County_Nonmovers",
                            "Unnamed: 25":"Previous_Residence_County_Nonmovers_MOE",
                            "Unnamed: 26":"Previous_Residence_Movers_within_United_States_or_Puerto_Rico",
                            "Unnamed: 27":"Previous_Residence_Movers_within_United_States_or_Puerto_Rico_MOE",
                            "Unnamed: 28":"Previous_Residence_Movers_within_Same_County",
                            "Unnamed: 29":"Previous_Residence_Movers_within_Same_County_MOE",
                            "Unnamed: 30":"Previous_Residence_Movers_to_Different_County_within_Same_State",
                            "Unnamed: 31":"Previous_Residence_Movers_within_Different_County_Same_State_MOE",
                            "Unnamed: 32":"Previous_Residence_Movers_to_Different_State",
                            "Unnamed: 33":"Previous_Residence_Movers_within_Different_State_MOE",
                            "Unnamed: 34":"Previous_Residence_Movers_to_PR",
                            "Unnamed: 35":"Previous_Residence_Movers_to_Puerto_Rico_MOE",
                            "Unnamed: 36":"Movers_in_County_to_County_Flow",
                            "Unnamed: 37":"Movers_in_County_to_County_Flow_MOE"}
                           , inplace = True)
current_residence_df.head()

,Current_Residence_State_Code,Current_Residence_FIPS_County_Code,Previous_Residence_State/U.S._Island Area/Foreign_Region_Code,Previous_Residence_FIPS_County_Code,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Population_1_Year_and_Over_MOE,Current_Residence_County_Nonmovers,Current_Residence_County_Nonmovers_MOE,...,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_within_Same_County_MOE,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_within_Different_County_Same_State_MOE,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_within_Different_State_MOE,Previous_Residence_Movers_to_PR,Previous_Residence_Movers_to_Puerto_Rico_MOE,Movers_in_County_to_County_Flow,Movers_in_County_to_County_Flow_MOE
0,Current Residence State Code,Current Residence FIPS County Code,Residence 1 Year Ago State/U.S. Island Area/Fo...,Residence 1 Year Ago FIPS County Code,State of Current Residence,County of Current Residence,County of Current Residence,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Movers in County-to-County Flow,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,Population 1 Year and Over,NaN,Nonmovers,NaN,...,Movers within Same County,NaN,"Movers to Different County, Same State",NaN,Movers to Different State,NaN,Movers to Puerto Rico,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,Estimate,MOE,Estimate,MOE,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
3,001,001,001,003,Alabama,Autauga County,54699,172,48066,987,...,13004,1466,3133,598,5592,827,NaN,NaN,25,26
4,001,001,001,005,Alabama,Autauga County,54699,172,48066,987,...,2325,523,1210,329,325,160,NaN,NaN,4,8

In [7]:
# Dropping first two rows and re-indexing
current_residence_df = current_residence_df.drop([0,1,2], axis=0, inplace=False)
current_residence_df = current_residence_df.reset_index(drop=True)
current_residence_df.head()

,Current_Residence_State_Code,Current_Residence_FIPS_County_Code,Previous_Residence_State/U.S._Island Area/Foreign_Region_Code,Previous_Residence_FIPS_County_Code,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Population_1_Year_and_Over_MOE,Current_Residence_County_Nonmovers,Current_Residence_County_Nonmovers_MOE,...,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_within_Same_County_MOE,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_within_Different_County_Same_State_MOE,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_within_Different_State_MOE,Previous_Residence_Movers_to_PR,Previous_Residence_Movers_to_Puerto_Rico_MOE,Movers_in_County_to_County_Flow,Movers_in_County_to_County_Flow_MOE
0,001,001,001,003,Alabama,Autauga County,54699,172,48066,987,...,13004,1466,3133,598,5592,827,NaN,NaN,25,26
1,001,001,001,005,Alabama,Autauga County,54699,172,48066,987,...,2325,523,1210,329,325,160,NaN,NaN,4,8
2,001,001,001,007,Alabama,Autauga County,54699,172,48066,987,...,784,352,1184,408,132,88,NaN,NaN,10,16
3,001,001,001,009,Alabama,Autauga County,54699,172,48066,987,...,2024,425,1818,436,583,209,NaN,NaN,3,6
4,001,001,001,015,Alabama,Autauga County,54699,172,48066,987,...,11467,1413,4162,565,2459,577,67,78,2,4

In [8]:
# View list of columns after renaming
list(current_residence_df.columns.values)

['Current_Residence_State_Code',
 'Current_Residence_FIPS_County_Code',
 'Previous_Residence_State/U.S._Island Area/Foreign_Region_Code',
 'Previous_Residence_FIPS_County_Code',
 'Current_Residence_State',
 'Current_Residence_County',
 'Current_Residence_County_Population',
 'Current_Residence_County_Population_1_Year_and_Over_MOE',
 'Current_Residence_County_Nonmovers',
 'Current_Residence_County_Nonmovers_MOE',
 'Current_Residence_Movers_within_US',
 'Current_Residence_Movers_within_United_States_1',
 'Current_Residence_Movers_within_Same_County',
 'Current_Residence_Movers_within_Same_County_MOE',
 'Current_Residence_Movers_from_Different_County_Same_State',
 'Current_Residence_Movers_from_Different_County_Same_State_MOE',
 'Current_Residence_Movers_from_Different_State',
 'Current_Residence_Movers_from_Different_State_MOE',
 'Current_Residence_Movers_from_Abroad',
 'Current_Residence_Movers_from_Abroad_MOE',
 'Previous_Residence_Movers_within_US_or_PR',
 'Previous_Residence_County',
 'Previous_Residence_County_Population',
 'Previous_Residence_County_Population_1_Year_and_Over_MOE',
 'Previous_Residence_County_Nonmovers',
 'Previous_Residence_County_Nonmovers_MOE',
 'Previous_Residence_Movers_within_United_States_or_Puerto_Rico',
 'Previous_Residence_Movers_within_United_States_or_Puerto_Rico_MOE',
 'Previous_Residence_Movers_within_Same_County',
 'Previous_Residence_Movers_within_Same_County_MOE',
 'Previous_Residence_Movers_to_Different_County_within_Same_State',
 'Previous_Residence_Movers_within_Different_County_Same_State_MOE',
 'Previous_Residence_Movers_to_Different_State',
 'Previous_Residence_Movers_within_Different_State_MOE',
 'Previous_Residence_Movers_to_PR',
 'Previous_Residence_Movers_to_Puerto_Rico_MOE',
 'Movers_in_County_to_County_Flow',
 'Movers_in_County_to_County_Flow_MOE']

In [9]:
#dropping non-relevant columns into a new dataframe
cleaned_cr_df=current_residence_df.drop(columns=["Current_Residence_State_Code",
                                                "Current_Residence_FIPS_County_Code",
                                                "Previous_Residence_State/U.S._Island Area/Foreign_Region_Code",
                                                "Previous_Residence_FIPS_County_Code",
                                                "Current_Residence_County_Population_1_Year_and_Over_MOE",
                                                "Current_Residence_County_Nonmovers_MOE",
                                                "Current_Residence_Movers_within_United_States_1",
                                                "Current_Residence_Movers_within_Same_County_MOE",
                                                "Current_Residence_Movers_from_Different_County_Same_State_MOE",
                                                "Current_Residence_Movers_from_Different_State_MOE",
                                                "Current_Residence_Movers_from_Abroad_MOE",
                                                "Previous_Residence_County_Population_1_Year_and_Over_MOE",
                                                "Previous_Residence_County_Nonmovers_MOE",
                                                "Previous_Residence_Movers_within_United_States_or_Puerto_Rico_MOE",
                                                "Previous_Residence_Movers_within_Same_County_MOE",
                                                "Previous_Residence_Movers_within_Different_County_Same_State_MOE",
                                                "Previous_Residence_Movers_within_Different_State_MOE",
                                                "Previous_Residence_Movers_to_Puerto_Rico_MOE",
                                                "Movers_in_County_to_County_Flow_MOE"], inplace=False)
cleaned_cr_df.head()

,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Nonmovers,Current_Residence_Movers_within_US,Current_Residence_Movers_within_Same_County,Current_Residence_Movers_from_Different_County_Same_State,Current_Residence_Movers_from_Different_State,Current_Residence_Movers_from_Abroad,Previous_Residence_Movers_within_US_or_PR,Previous_Residence_County,Previous_Residence_County_Population,Previous_Residence_County_Nonmovers,Previous_Residence_Movers_within_United_States_or_Puerto_Rico,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_to_PR,Movers_in_County_to_County_Flow
0,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Baldwin County,207884,186155,21729,13004,3133,5592,NaN,25
1,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Barbour County,25266,21406,3860,2325,1210,325,NaN,4
2,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Bibb County,21960,19860,2100,784,1184,132,NaN,10
3,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Blount County,57849,53424,4425,2024,1818,583,NaN,3
4,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Calhoun County,113102,94947,18088,11467,4162,2459,67,2

In [10]:
# View list of columns after dropping columns
list(cleaned_cr_df.columns.values)

['Current_Residence_State',
 'Current_Residence_County',
 'Current_Residence_County_Population',
 'Current_Residence_County_Nonmovers',
 'Current_Residence_Movers_within_US',
 'Current_Residence_Movers_within_Same_County',
 'Current_Residence_Movers_from_Different_County_Same_State',
 'Current_Residence_Movers_from_Different_State',
 'Current_Residence_Movers_from_Abroad',
 'Previous_Residence_Movers_within_US_or_PR',
 'Previous_Residence_County',
 'Previous_Residence_County_Population',
 'Previous_Residence_County_Nonmovers',
 'Previous_Residence_Movers_within_United_States_or_Puerto_Rico',
 'Previous_Residence_Movers_within_Same_County',
 'Previous_Residence_Movers_to_Different_County_within_Same_State',
 'Previous_Residence_Movers_to_Different_State',
 'Previous_Residence_Movers_to_PR',
 'Movers_in_County_to_County_Flow']

In [11]:
cleaned_cr_df.dtypes

Current_Residence_State                                            object
Current_Residence_County                                           object
Current_Residence_County_Population                                object
Current_Residence_County_Nonmovers                                 object
Current_Residence_Movers_within_US                                 object
Current_Residence_Movers_within_Same_County                        object
Current_Residence_Movers_from_Different_County_Same_State          object
Current_Residence_Movers_from_Different_State                      object
Current_Residence_Movers_from_Abroad                               object
Previous_Residence_Movers_within_US_or_PR                          object
Previous_Residence_County                                          object
Previous_Residence_County_Population                               object
Previous_Residence_County_Nonmovers                                object
Previous_Residence_Movers_within_United_States_or_Puerto_Rico      object
Previous_Residence_Movers_within_Same_County                       object
Previous_Residence_Movers_to_Different_County_within_Same_State    object
Previous_Residence_Movers_to_Different_State                       object
Previous_Residence_Movers_to_PR                                    object
Movers_in_County_to_County_Flow                                    object
dtype: object

In [12]:
# Add a “County and state of current residence” column 
cleaned_cr_df['Current_Residence_County_State'] = cleaned_cr_df['Current_Residence_County'] +', '+ cleaned_cr_df['Current_Residence_State']
cleaned_cr_df.head()

,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Nonmovers,Current_Residence_Movers_within_US,Current_Residence_Movers_within_Same_County,Current_Residence_Movers_from_Different_County_Same_State,Current_Residence_Movers_from_Different_State,Current_Residence_Movers_from_Abroad,Previous_Residence_Movers_within_US_or_PR,Previous_Residence_County,Previous_Residence_County_Population,Previous_Residence_County_Nonmovers,Previous_Residence_Movers_within_United_States_or_Puerto_Rico,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_to_PR,Movers_in_County_to_County_Flow,Current_Residence_County_State
0,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Baldwin County,207884,186155,21729,13004,3133,5592,NaN,25,"Autauga County, Alabama"
1,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Barbour County,25266,21406,3860,2325,1210,325,NaN,4,"Autauga County, Alabama"
2,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Bibb County,21960,19860,2100,784,1184,132,NaN,10,"Autauga County, Alabama"
3,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Blount County,57849,53424,4425,2024,1818,583,NaN,3,"Autauga County, Alabama"
4,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Calhoun County,113102,94947,18088,11467,4162,2459,67,2,"Autauga County, Alabama"

In [20]:
# Add a “County and state of earlier residence” column
cleaned_cr_df['Previous_Residence_County_State'] = cleaned_cr_df['Previous_Residence_County'] +', '+ cleaned_cr_df['Previous_Residence_Movers_within_US_or_PR']
cleaned_cr_df.head(50)

,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Nonmovers,Current_Residence_Movers_within_US,Current_Residence_Movers_within_Same_County,Current_Residence_Movers_from_Different_County_Same_State,Current_Residence_Movers_from_Different_State,Current_Residence_Movers_from_Abroad,Previous_Residence_Movers_within_US_or_PR,...,Previous_Residence_County_Population,Previous_Residence_County_Nonmovers,Previous_Residence_Movers_within_United_States_or_Puerto_Rico,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_to_PR,Movers_in_County_to_County_Flow,Current_Residence_County_State,Previous_Residence_County_State
0,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,207884,186155,21729,13004,3133,5592,NaN,25,"Autauga County, Alabama","Baldwin County, Alabama"
1,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,25266,21406,3860,2325,1210,325,NaN,4,"Autauga County, Alabama","Barbour County, Alabama"
2,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,21960,19860,2100,784,1184,132,NaN,10,"Autauga County, Alabama","Bibb County, Alabama"
3,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,57849,53424,4425,2024,1818,583,NaN,3,"Autauga County, Alabama","Blount County, Alabama"
4,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,113102,94947,18088,11467,4162,2459,67,2,"Autauga County, Alabama","Calhoun County, Alabama"
5,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,43801,39270,4531,2835,1234,462,NaN,11,"Autauga County, Alabama","Chilton County, Alabama"
6,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,24100,22249,1851,1146,413,292,NaN,34,"Autauga County, Alabama","Clarke County, Alabama"
7,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,12488,11909,579,191,357,31,NaN,44,"Autauga County, Alabama","Conecuh County, Alabama"
8,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,47147,39659,7488,3126,2289,2073,NaN,75,"Autauga County, Alabama","Dale County, Alabama"
9,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,39054,34106,4948,3123,1392,433,NaN,129,"Autauga County, Alabama","Dallas County, Alabama"
10,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,78802,68625,10177,4551,4515,1111,NaN,547,"Autauga County, Alabama","Elmore County, Alabama"
11,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,101090,87863,13227,9063,2435,1729,NaN,1,"Autauga County, Alabama","Etowah County, Alabama"
12,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,650812,547909,102903,71086,18532,13285,NaN,17,"Autauga County, Alabama","Jefferson County, Alabama"
13,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,88588,75964,12624,8429,2602,1593,NaN,47,"Autauga County, Alabama","Lauderdale County, Alabama"
14,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,153728,128091,25637,14360,4949,6328,NaN,182,"Autauga County, Alabama","Lee County, Alabama"
15,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,90955,81011,9944,4943,3464,1537,NaN,20,"Autauga County, Alabama","Limestone County, Alabama"
16,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,355157,298126,57019,37693,8736,10590,12,11,"Autauga County, Alabama","Madison County, Alabama"
17,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,30254,27265,2989,1505,1079,405,NaN,1,"Autauga County, Alabama","Marion County, Alabama"
18,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,94779,83310,11469,6142,3745,1582,NaN,27,"Autauga County, Alabama","Marshall County, Alabama"
19,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,411234,358901,52333,37330,5941,9062,NaN,10,"Autauga County, Alabama","Mobile County, Alabama"
20,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,220735,177968,42741,29974,6819,5948,26,524,"Autauga County, Alabama","Montgomery County, Alabama"
21,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,55808,46872,8936,3938,1524,3474,NaN,21,"Autauga County, Alabama","Russell County, Alabama"
22,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,87046,76746,10300,5410,4028,862,NaN,58,"Autauga County, Alabama","St. Clair County, Alabama"
23,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,207819,182989,24830,12235,8024,4571,NaN,41,"Autauga County, Alabama","Shelby County, Alabama"
24,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,40516,36101,4415,1860,1929,626,NaN,6,"Autauga County, Alabama","Tallapoosa County, Alabama"
25,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,62018,54678,7340,5170,1762,408,NaN,16,"Autauga County, Alabama","Walker County, Alabama"
26,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,10912,9783,1129,348,711,70,NaN,149,"Autauga County, Alabama","Wilcox County, Alabama"
27,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Arizona,...,123826,103962,19864,8467,4877,6520,NaN,81,"Autauga County, Alabama","Cochise County, Arizona"
28,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,California,...,145893,121820,24073,13940,6521,3612,NaN,9,"Autauga County, Alabama","Kings County, California"
29,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Florida,...,567736,496449,71225,46106,11242,13877,62,8,"Autauga County, Alabama","Brevard County, Florida"
30,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Florida,...,1382753,1153667,228550,152369,43546,32635,536,33,"Autauga County, Alabama","Hillsborough County, Florida"
31,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Florida,...,168391,141020,27371,11927,7788,7656,NaN,42,"Autauga County, Alabama","Santa Rosa County, Florida"
32,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Georgia,...,141073,122682,18391,10245,5952,2194,NaN,49,"Autauga County, Alabama","Coweta County, Georgia"
33,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Georgia,...,898878,789036,109695,55476,35895,18324,147,42,"Autauga County, Alabama","Gwinnett County, Georgia"
34,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Georgia,...,10744,9183,1561,1199,239,123,NaN,8,"Autauga County, Alabama","Pulaski County, Georgia"
35,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Illinois,...,5186144,4486555,699293,483728,81192,134373,296,16,"Autauga County, Alabama","Cook County, Illinois"
36,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Indiana,...,948530,803104,145382,89544,33936,21902,44,8,"Autauga County, Alabama","Marion County, Indiana"
37,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Kentucky,...,19492,17043,2449,847,1430,172,NaN,29,"Autauga County, Alabama","Adair County, Kentucky"
38,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Louisiana,...,125231,109660,15571,7120,4418,4033,NaN,158,"Autauga County, Alabama","Bossier Parish, Louisiana"
39,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Maryland,...,560635,481055,79553,41518,16014,22021,27,38,"Autauga County, Alabama","Anne Arundel County, Maryland"
40,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Maryland,...,247069,217864,29205,15476,6498,7231,NaN,52,"Autauga County, Alabama","Frederick County, Maryland"
41,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Michigan,...,254778,208118,46660,31136,9439,6085,NaN,35,"Autauga County, Alabama","Kalamazoo County, Michigan"
42,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Minnesota,...,13667,11988,1679,719,599,361,NaN,2,"Autauga County, Alabama","Wadena County, Minnesota"
43,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Mississippi,...,47431,37286,10145,5656,2356,2133,NaN,20,"Autauga County, Alabama","Oktibbeha County, Mississippi"
44,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Missouri,...,981923,845199,136724,83378,29055,24291,NaN,37,"Autauga County, Alabama","St. Louis County, Missouri"
45,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,New Jersey,...,328839,296670,32117,10594,11021,10502,52,7,"Autauga County, Alabama","Somerset County, New Jersey"
46,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,New Mexico,...,48841,38829,10012,5673,1306,3033,NaN,138,"Autauga County, Alabama","Curry County, New Mexico"
47,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,North Carolina,...,369075,318398,50677,29946,12710,8021,NaN,5,"Autauga County, Alabama","Forsyth County, North Carolina"
48,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Oklahoma,...,44256,37138,7118,4121,1964,1033,NaN,8,"Autauga County, Alabama","Stephens County, Oklahoma"
49,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Oregon,...,75515,63224,12291,7902,2023,2366,NaN,13,"Autauga County, Alabama","Umatilla County, Oregon"

In [14]:
# Replace NaN with 0
cleaned_cr_df

In [16]:
# Export to csv file
cleaned_cr_df.to_csv(".\Resources\cleaned-county-to-county-2015-2019-current-residence-sort.csv", header=True, index=False)