In [1]:
import pandas as pd

In [2]:
# Read the excel worksheets into one dataframe
current_residence_df = pd.concat(pd.read_excel (".\Resources\county-to-county-2015-2019-current-residence-sort.xlsx", sheet_name=None), ignore_index=True)

In [3]:
# View top 10 rows of the dataframe
current_residence_df.head(10)

,Table with column headers in rows 2 through 4.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,Current Residence State Code,Current Residence FIPS County Code,Residence 1 Year Ago State/U.S. Island Area/Fo...,Residence 1 Year Ago FIPS County Code,State of Current Residence,County of Current Residence,County of Current Residence,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Movers in County-to-County Flow,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,Population 1 Year and Over,NaN,Nonmovers,NaN,...,Movers within Same County,NaN,"Movers to Different County, Same State",NaN,Movers to Different State,NaN,Movers to Puerto Rico,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,Estimate,MOE,Estimate,MOE,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
3,001,001,001,003,Alabama,Autauga County,54699,172,48066,987,...,13004,1466,3133,598,5592,827,NaN,NaN,25,26
4,001,001,001,005,Alabama,Autauga County,54699,172,48066,987,...,2325,523,1210,329,325,160,NaN,NaN,4,8
5,001,001,001,007,Alabama,Autauga County,54699,172,48066,987,...,784,352,1184,408,132,88,NaN,NaN,10,16
6,001,001,001,009,Alabama,Autauga County,54699,172,48066,987,...,2024,425,1818,436,583,209,NaN,NaN,3,6
7,001,001,001,015,Alabama,Autauga County,54699,172,48066,987,...,11467,1413,4162,565,2459,577,67,78,2,4
8,001,001,001,021,Alabama,Autauga County,54699,172,48066,987,...,2835,814,1234,377,462,231,NaN,NaN,11,16
9,001,001,001,025,Alabama,Autauga County,54699,172,48066,987,...,1146,376,413,178,292,206,NaN,NaN,34,52

In [4]:
# View last 10 rows of the dataframe
current_residence_df.tail(10)

,Table with column headers in rows 2 through 4.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
278791,072,153,072,151,Puerto Rico,Yauco Municipio,35149,127,33995,457,...,1253,536,766,408,1317,447,NaN,NaN,71,107
278792,072,153,CAR,NaN,Puerto Rico,Yauco Municipio,35149,127,33995,457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,34
278793,072,153,SAM,NaN,Puerto Rico,Yauco Municipio,35149,127,33995,457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,86
278794,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278795,"1Includes Puerto Rico, U.S. Island Areas, and ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278796,2Estimate is movers within the United States f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278797,Blank cells represent estimates that are not a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278798,MOE - Margin of error based on 90% confidence ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278799,The Census Bureau reviewed this data product f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278800,"Source: U.S. Census Bureau, 2015-2019 American...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# View list of columns
list(current_residence_df.columns.values)

['Table with column headers in rows 2 through 4.',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37']

In [6]:
#Rename columns and replace spaces with underscore
current_residence_df.rename(columns = {"Table with column headers in rows 2 through 4.":"Current_Residence_State_Code",
                            "Unnamed: 1":"Current_Residence_FIPS_County_Code",
                            "Unnamed: 2":"Previous_Residence_State/U.S._Island Area/Foreign_Region_Code",
                            "Unnamed: 3":"Previous_Residence_FIPS_County_Code",
                            "Unnamed: 4":"Current_Residence_State",
                            "Unnamed: 5":"Current_Residence_County",
                            "Unnamed: 6":"Current_Residence_County_Population",
                            "Unnamed: 7":"Current_Residence_County_Population_1_Year_and_Over_MOE",
                            "Unnamed: 8":"Current_Residence_County_Nonmovers",
                            "Unnamed: 9":"Current_Residence_County_Nonmovers_MOE",
                            "Unnamed: 10":"Current_Residence_Movers_within_US",
                            "Unnamed: 11":"Current_Residence_Movers_within_United_States_1",
                            "Unnamed: 12":"Current_Residence_Movers_within_Same_County",
                            "Unnamed: 13":"Current_Residence_Movers_within_Same_County_MOE",
                            "Unnamed: 14":"Current_Residence_Movers_from_Different_County_Same_State",
                            "Unnamed: 15":"Current_Residence_Movers_from_Different_County_Same_State_MOE",
                            "Unnamed: 16":"Current_Residence_Movers_from_Different_State",
                            "Unnamed: 17":"Current_Residence_Movers_from_Different_State_MOE",
                            "Unnamed: 18":"Current_Residence_Movers_from_Abroad",
                            "Unnamed: 19":"Current_Residence_Movers_from_Abroad_MOE",
                            "Unnamed: 20":"Previous_Residence_Movers_within_US_or_PR",
                            "Unnamed: 21":"Previous_Residence_County",
                            "Unnamed: 22":"Previous_Residence_County_Population",
                            "Unnamed: 23":"Previous_Residence_County_Population_1_Year_and_Over_MOE",
                            "Unnamed: 24":"Previous_Residence_County_Nonmovers",
                            "Unnamed: 25":"Previous_Residence_County_Nonmovers_MOE",
                            "Unnamed: 26":"Previous_Residence_Movers_within_United_States_or_Puerto_Rico",
                            "Unnamed: 27":"Previous_Residence_Movers_within_United_States_or_Puerto_Rico_MOE",
                            "Unnamed: 28":"Previous_Residence_Movers_within_Same_County",
                            "Unnamed: 29":"Previous_Residence_Movers_within_Same_County_MOE",
                            "Unnamed: 30":"Previous_Residence_Movers_to_Different_County_within_Same_State",
                            "Unnamed: 31":"Previous_Residence_Movers_within_Different_County_Same_State_MOE",
                            "Unnamed: 32":"Previous_Residence_Movers_to_Different_State",
                            "Unnamed: 33":"Previous_Residence_Movers_within_Different_State_MOE",
                            "Unnamed: 34":"Previous_Residence_Movers_to_PR",
                            "Unnamed: 35":"Previous_Residence_Movers_to_Puerto_Rico_MOE",
                            "Unnamed: 36":"Movers_in_County_to_County_Flow",
                            "Unnamed: 37":"Movers_in_County_to_County_Flow_MOE"}
                           , inplace = True)
current_residence_df.head()

,Current_Residence_State_Code,Current_Residence_FIPS_County_Code,Previous_Residence_State/U.S._Island Area/Foreign_Region_Code,Previous_Residence_FIPS_County_Code,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Population_1_Year_and_Over_MOE,Current_Residence_County_Nonmovers,Current_Residence_County_Nonmovers_MOE,...,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_within_Same_County_MOE,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_within_Different_County_Same_State_MOE,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_within_Different_State_MOE,Previous_Residence_Movers_to_PR,Previous_Residence_Movers_to_Puerto_Rico_MOE,Movers_in_County_to_County_Flow,Movers_in_County_to_County_Flow_MOE
0,Current Residence State Code,Current Residence FIPS County Code,Residence 1 Year Ago State/U.S. Island Area/Fo...,Residence 1 Year Ago FIPS County Code,State of Current Residence,County of Current Residence,County of Current Residence,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Movers in County-to-County Flow,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,Population 1 Year and Over,NaN,Nonmovers,NaN,...,Movers within Same County,NaN,"Movers to Different County, Same State",NaN,Movers to Different State,NaN,Movers to Puerto Rico,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,Estimate,MOE,Estimate,MOE,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
3,001,001,001,003,Alabama,Autauga County,54699,172,48066,987,...,13004,1466,3133,598,5592,827,NaN,NaN,25,26
4,001,001,001,005,Alabama,Autauga County,54699,172,48066,987,...,2325,523,1210,329,325,160,NaN,NaN,4,8

In [7]:
# Dropping first two rows and re-indexing
current_residence_df = current_residence_df.drop([0,1,2], axis=0, inplace=False)
current_residence_df = current_residence_df.reset_index(drop=True)
current_residence_df.head()

,Current_Residence_State_Code,Current_Residence_FIPS_County_Code,Previous_Residence_State/U.S._Island Area/Foreign_Region_Code,Previous_Residence_FIPS_County_Code,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Population_1_Year_and_Over_MOE,Current_Residence_County_Nonmovers,Current_Residence_County_Nonmovers_MOE,...,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_within_Same_County_MOE,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_within_Different_County_Same_State_MOE,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_within_Different_State_MOE,Previous_Residence_Movers_to_PR,Previous_Residence_Movers_to_Puerto_Rico_MOE,Movers_in_County_to_County_Flow,Movers_in_County_to_County_Flow_MOE
0,001,001,001,003,Alabama,Autauga County,54699,172,48066,987,...,13004,1466,3133,598,5592,827,NaN,NaN,25,26
1,001,001,001,005,Alabama,Autauga County,54699,172,48066,987,...,2325,523,1210,329,325,160,NaN,NaN,4,8
2,001,001,001,007,Alabama,Autauga County,54699,172,48066,987,...,784,352,1184,408,132,88,NaN,NaN,10,16
3,001,001,001,009,Alabama,Autauga County,54699,172,48066,987,...,2024,425,1818,436,583,209,NaN,NaN,3,6
4,001,001,001,015,Alabama,Autauga County,54699,172,48066,987,...,11467,1413,4162,565,2459,577,67,78,2,4

In [8]:
# View list of columns after renaming
list(current_residence_df.columns.values)

['Current_Residence_State_Code',
 'Current_Residence_FIPS_County_Code',
 'Previous_Residence_State/U.S._Island Area/Foreign_Region_Code',
 'Previous_Residence_FIPS_County_Code',
 'Current_Residence_State',
 'Current_Residence_County',
 'Current_Residence_County_Population',
 'Current_Residence_County_Population_1_Year_and_Over_MOE',
 'Current_Residence_County_Nonmovers',
 'Current_Residence_County_Nonmovers_MOE',
 'Current_Residence_Movers_within_US',
 'Current_Residence_Movers_within_United_States_1',
 'Current_Residence_Movers_within_Same_County',
 'Current_Residence_Movers_within_Same_County_MOE',
 'Current_Residence_Movers_from_Different_County_Same_State',
 'Current_Residence_Movers_from_Different_County_Same_State_MOE',
 'Current_Residence_Movers_from_Different_State',
 'Current_Residence_Movers_from_Different_State_MOE',
 'Current_Residence_Movers_from_Abroad',
 'Current_Residence_Movers_from_Abroad_MOE',
 'Previous_Residence_Movers_within_US_or_PR',
 'Previous_Residence_County',
 'Previous_Residence_County_Population',
 'Previous_Residence_County_Population_1_Year_and_Over_MOE',
 'Previous_Residence_County_Nonmovers',
 'Previous_Residence_County_Nonmovers_MOE',
 'Previous_Residence_Movers_within_United_States_or_Puerto_Rico',
 'Previous_Residence_Movers_within_United_States_or_Puerto_Rico_MOE',
 'Previous_Residence_Movers_within_Same_County',
 'Previous_Residence_Movers_within_Same_County_MOE',
 'Previous_Residence_Movers_to_Different_County_within_Same_State',
 'Previous_Residence_Movers_within_Different_County_Same_State_MOE',
 'Previous_Residence_Movers_to_Different_State',
 'Previous_Residence_Movers_within_Different_State_MOE',
 'Previous_Residence_Movers_to_PR',
 'Previous_Residence_Movers_to_Puerto_Rico_MOE',
 'Movers_in_County_to_County_Flow',
 'Movers_in_County_to_County_Flow_MOE']

In [9]:
#dropping non-relevant columns into a new dataframe
cleaned_cr_df=current_residence_df.drop(columns=["Current_Residence_State_Code",
                                                "Current_Residence_FIPS_County_Code",
                                                "Previous_Residence_State/U.S._Island Area/Foreign_Region_Code",
                                                "Previous_Residence_FIPS_County_Code",
                                                "Current_Residence_County_Population_1_Year_and_Over_MOE",
                                                "Current_Residence_County_Nonmovers_MOE",
                                                "Current_Residence_Movers_within_United_States_1",
                                                "Current_Residence_Movers_within_Same_County_MOE",
                                                "Current_Residence_Movers_from_Different_County_Same_State_MOE",
                                                "Current_Residence_Movers_from_Different_State_MOE",
                                                "Current_Residence_Movers_from_Abroad_MOE",
                                                "Previous_Residence_County_Population_1_Year_and_Over_MOE",
                                                "Previous_Residence_County_Nonmovers_MOE",
                                                "Previous_Residence_Movers_within_United_States_or_Puerto_Rico_MOE",
                                                "Previous_Residence_Movers_within_Same_County_MOE",
                                                "Previous_Residence_Movers_within_Different_County_Same_State_MOE",
                                                "Previous_Residence_Movers_within_Different_State_MOE",
                                                "Previous_Residence_Movers_to_Puerto_Rico_MOE",
                                                "Movers_in_County_to_County_Flow_MOE"], inplace=False)
cleaned_cr_df.head()

,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Nonmovers,Current_Residence_Movers_within_US,Current_Residence_Movers_within_Same_County,Current_Residence_Movers_from_Different_County_Same_State,Current_Residence_Movers_from_Different_State,Current_Residence_Movers_from_Abroad,Previous_Residence_Movers_within_US_or_PR,Previous_Residence_County,Previous_Residence_County_Population,Previous_Residence_County_Nonmovers,Previous_Residence_Movers_within_United_States_or_Puerto_Rico,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_to_PR,Movers_in_County_to_County_Flow
0,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Baldwin County,207884,186155,21729,13004,3133,5592,NaN,25
1,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Barbour County,25266,21406,3860,2325,1210,325,NaN,4
2,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Bibb County,21960,19860,2100,784,1184,132,NaN,10
3,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Blount County,57849,53424,4425,2024,1818,583,NaN,3
4,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Calhoun County,113102,94947,18088,11467,4162,2459,67,2

In [10]:
# View list of columns after dropping columns
list(cleaned_cr_df.columns.values)

['Current_Residence_State',
 'Current_Residence_County',
 'Current_Residence_County_Population',
 'Current_Residence_County_Nonmovers',
 'Current_Residence_Movers_within_US',
 'Current_Residence_Movers_within_Same_County',
 'Current_Residence_Movers_from_Different_County_Same_State',
 'Current_Residence_Movers_from_Different_State',
 'Current_Residence_Movers_from_Abroad',
 'Previous_Residence_Movers_within_US_or_PR',
 'Previous_Residence_County',
 'Previous_Residence_County_Population',
 'Previous_Residence_County_Nonmovers',
 'Previous_Residence_Movers_within_United_States_or_Puerto_Rico',
 'Previous_Residence_Movers_within_Same_County',
 'Previous_Residence_Movers_to_Different_County_within_Same_State',
 'Previous_Residence_Movers_to_Different_State',
 'Previous_Residence_Movers_to_PR',
 'Movers_in_County_to_County_Flow']

In [11]:
cleaned_cr_df.dtypes

Current_Residence_State                                            object
Current_Residence_County                                           object
Current_Residence_County_Population                                object
Current_Residence_County_Nonmovers                                 object
Current_Residence_Movers_within_US                                 object
Current_Residence_Movers_within_Same_County                        object
Current_Residence_Movers_from_Different_County_Same_State          object
Current_Residence_Movers_from_Different_State                      object
Current_Residence_Movers_from_Abroad                               object
Previous_Residence_Movers_within_US_or_PR                          object
Previous_Residence_County                                          object
Previous_Residence_County_Population                               object
Previous_Residence_County_Nonmovers                                object
Previous_Residence_Movers_within_United_States_or_Puerto_Rico      object
Previous_Residence_Movers_within_Same_County                       object
Previous_Residence_Movers_to_Different_County_within_Same_State    object
Previous_Residence_Movers_to_Different_State                       object
Previous_Residence_Movers_to_PR                                    object
Movers_in_County_to_County_Flow                                    object
dtype: object

In [12]:
# Add a “County and state of current residence” column 
cleaned_cr_df['Current_Residence_County_State'] = cleaned_cr_df['Current_Residence_County'] +', '+ cleaned_cr_df['Current_Residence_State']
cleaned_cr_df.head()

,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Nonmovers,Current_Residence_Movers_within_US,Current_Residence_Movers_within_Same_County,Current_Residence_Movers_from_Different_County_Same_State,Current_Residence_Movers_from_Different_State,Current_Residence_Movers_from_Abroad,Previous_Residence_Movers_within_US_or_PR,Previous_Residence_County,Previous_Residence_County_Population,Previous_Residence_County_Nonmovers,Previous_Residence_Movers_within_United_States_or_Puerto_Rico,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_to_PR,Movers_in_County_to_County_Flow,Current_Residence_County_State
0,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Baldwin County,207884,186155,21729,13004,3133,5592,NaN,25,"Autauga County, Alabama"
1,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Barbour County,25266,21406,3860,2325,1210,325,NaN,4,"Autauga County, Alabama"
2,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Bibb County,21960,19860,2100,784,1184,132,NaN,10,"Autauga County, Alabama"
3,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Blount County,57849,53424,4425,2024,1818,583,NaN,3,"Autauga County, Alabama"
4,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,Calhoun County,113102,94947,18088,11467,4162,2459,67,2,"Autauga County, Alabama"

In [13]:
# Add a “County and state of earlier residence” column
cleaned_cr_df['Previous_Residence_County_State'] = cleaned_cr_df['Previous_Residence_County'] +', '+ cleaned_cr_df['Previous_Residence_Movers_within_US_or_PR']
cleaned_cr_df.head()

,Current_Residence_State,Current_Residence_County,Current_Residence_County_Population,Current_Residence_County_Nonmovers,Current_Residence_Movers_within_US,Current_Residence_Movers_within_Same_County,Current_Residence_Movers_from_Different_County_Same_State,Current_Residence_Movers_from_Different_State,Current_Residence_Movers_from_Abroad,Previous_Residence_Movers_within_US_or_PR,...,Previous_Residence_County_Population,Previous_Residence_County_Nonmovers,Previous_Residence_Movers_within_United_States_or_Puerto_Rico,Previous_Residence_Movers_within_Same_County,Previous_Residence_Movers_to_Different_County_within_Same_State,Previous_Residence_Movers_to_Different_State,Previous_Residence_Movers_to_PR,Movers_in_County_to_County_Flow,Current_Residence_County_State,Previous_Residence_County_State
0,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,207884,186155,21729,13004,3133,5592,NaN,25,"Autauga County, Alabama","Baldwin County, Alabama"
1,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,25266,21406,3860,2325,1210,325,NaN,4,"Autauga County, Alabama","Barbour County, Alabama"
2,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,21960,19860,2100,784,1184,132,NaN,10,"Autauga County, Alabama","Bibb County, Alabama"
3,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,57849,53424,4425,2024,1818,583,NaN,3,"Autauga County, Alabama","Blount County, Alabama"
4,Alabama,Autauga County,54699,48066,6539,2976,2015,1548,94,Alabama,...,113102,94947,18088,11467,4162,2459,67,2,"Autauga County, Alabama","Calhoun County, Alabama"

In [14]:
# drop rows with NaN

In [16]:
# Export to csv file
cleaned_cr_df.to_csv(".\Resources\cleaned-county-to-county-2015-2019-current-residence-sort.csv", header=True, index=False)